wzolleis/djk-kicker

- app/components/nav/appLinks.ts
- app/components/nav/appMenu.tsx
- app/routes/application/admin.test.tsx
- app/routes/application/admin.tsx
- app/routes/application/admin/events.tsx
- app/routes/application/admin/index.tsx
- package-lock.json
- package.json
- test/setup-test-env.ts
- tsconfig.json
- vitest.config.ts
Templates für die Administration, Menü angepasst u. vitest so konfiguriert, dass die Tests laufen.
> admin panels + vitest config

- .idea/codeStyles/Project.xml
- app/components/i18n/messages.ts
- app/components/nav/appLinks.ts
- app/routes/application/admin.tsx
- app/routes/application/admin/index.tsx
Die Landingpage verlinkt auf die Unterseiten.
> Landing-Page für die Verwaltung

- app/components/admin/games/GameView.tsx
- app/components/i18n/messages.ts
- app/models/games.server.ts
- app/routes/application/admin/games.tsx
- app/routes/application/admin/games/new.tsx
- app/utils.ts
- prisma/schema.prisma
* Neues Spiel anlegen
* gameTime ist ein Date, input-Type = datetime-local
* link ist optional
> * Formular u. Action um ein Spiel anzulegen

- app/components/i18n/messages.ts
- app/models/admin.games.server.ts
- app/routes/application/admin/games.tsx
- app/routes/application/admin/games/$gameId.tsx
- app/routes/application/admin/games/new.tsx
- app/routes/references.tsx
- prettier.config.js
- prisma/schema.prisma
* useEffect um den Wert im Select zu setzen, form.reset und setzen des Default-Values funktioniert nicht.
> * Spielort kann jetzt auch gespeichert werden.

- README.md
> README für Projektsetup angepasst.

- app/components/game/GameCard.tsx
- app/components/game/players/PlayerCard.tsx
- app/components/i18n/messages.ts
- app/models/games.server.ts
- app/routes/application.tsx
- app/utils.ts
* PR für den aktuellen Stand von Tim
> Styling + Mittwoch-Algorithmus

- app/components/game/Players.tsx
- app/components/game/players/PlayerCard.tsx
- app/components/i18n/messages.ts
- app/components/player/EditPlayerStatusForm.tsx
- app/components/warnings/NoTokenWarning.tsx
- app/routes/application/games/$gameId.tsx
- app/routes/application/games/$gameId/index.tsx
- app/routes/application/games/$gameId/player/$playerId.tsx
- app/utils.ts
- app/utils/session.server.ts
- app/utils/token.server.ts
- package-lock.json
- package.json
> Added tokens for player authentification

- app/components/i18n/messages.ts
- app/helpers/mail/mailsender.ts
- app/models/admin.games.mails.server.ts
- app/models/player.server.ts
- app/routes/application/admin/games/$gameId.einladung.tsx
> Einladungslink verschicken

- .idea/dataSources.xml
- app/components/common/buttons/DefaultButton.tsx
- app/components/i18n/messages.ts
- app/components/nav/AppNavBar.tsx
- app/components/nav/appLinks.ts
- app/components/users/admin/AdminTable.tsx
- app/components/users/admin/table/AdminRole.tsx
- app/components/users/admin/table/AdminTableRow.tsx
- app/components/users/player/table/PlayerTable.tsx
- app/components/users/player/table/PlayerTableRow.tsx
- app/models/classes/AdminTokenOption.ts
- app/models/user.server.ts
- app/routes/application/admin.tsx
- app/routes/application/admin/users.tsx
- app/routes/application/admin/users/new.tsx
- app/routes/application/games/$gameId.tsx
- app/utils/token.server.ts
- prisma/schema.prisma
- added usermanagement (wip) 
- fixed navbar
> [WIP] User Management

- app/components/i18n/messages.ts
- app/models/admin.games.mails.server.ts
- app/routes/application/admin/games/$gameId.absage.tsx
- app/routes/application/admin/games/$gameId.tsx
- app/routes/application/admin/games/$gameId.zusage.tsx
- app/routes/application/admin/games/$gameId/actions.tsx
- package-lock.json
* Formulare und Mails für Zu- bzw. Absage
* Depencency Updates
> Verschicke Ab- u. Zusage-Mail

- app/components/game/Players.tsx
- app/routes/application/admin/games/$gameId.einladung.tsx
- app/routes/application/games/$gameId/index.tsx
Button für neue Spieler nicht sichtbar ohne Berechtigung
> Button für neue Spieler nicht sichtbar ohne Berechtigung

- app/routes/application/index.tsx
- app/routes/index.tsx
- app/routes/login.tsx
Als Einstieg ist immer application/games gesetzt.
> Navigation immer auf die Games-Seite

- app/components/common/buttons/status/SetStatusButton.tsx
- app/components/player/CreatePlayerForm.tsx
- app/components/player/EditPlayerStatusForm.tsx
- app/config/filters.ts
- app/helpers/formdata/feedback.formdata.server.ts
- app/routes/application/admin/games/new.tsx
- app/routes/application/games/$gameId/player/$playerId.tsx
- app/routes/application/player/create.tsx
* Mail mit "@"
* Leerzeichen entfernen
> * Mailadresse validieren + Leerzeichen

- app/components/actions/ActionCard.tsx
- app/components/common/tags/PlayerStatusTag.tsx
- app/components/game/admin/EditGameForm.tsx
- app/components/game/admin/functionButtons/SaveGame.tsx
- app/components/game/feedback/ConfirmedPlayersCounter.tsx
- app/components/game/feedback/DeclinedPlayersCounter.tsx
- app/components/game/feedback/UndecidedPlayersCounter.tsx
- app/components/game/feedback/UnknownPlayersCounter.tsx
- app/components/game/forms/CreateGameForm.tsx
- app/components/i18n/messages.ts
- app/components/player/CreatePlayerForm.tsx
- app/components/player/EditPlayerStatusForm.tsx
- app/config/action.ts
- app/config/index.ts
- app/config/locations.ts
- app/config/status.ts
- app/models/feedback.server.ts
- app/routes/application/admin/games/$gameId.tsx
- app/routes/application/admin/games/$gameId/actions.tsx
- app/routes/application/admin/games/$gameId/invite.tsx
- app/routes/application/admin/games/$gameId/status.tsx
- app/routes/application/index.tsx
- app/utils/game.server.ts
- app/utils/statusUtils.ts
Verschiebe Werte aus 118n nach config.
> * Refactoring der Konfigurations-Werte

- app/components/common/counter/PlayerCount.tsx
- app/components/common/error/ErrorComponent.tsx
- app/components/i18n/messages.ts
- app/components/nav/appLinks.ts
- app/components/nav/appMenu.tsx
- app/helpers/constants/routeLinks.ts
- app/routes/application/dashboard/index.tsx
- app/routes/application/games/$gameId.tsx
- app/routes/application/games/$gameId/player/$playerId/index.tsx
bugfix: Wenn der Spieler nicht authenticated ist (kein cookie), ist ein Fehler aufgetreten, da an verschiedenen Stellen ein Spieler erwartet wurde.
Dashboard-Link
PlayerCount mit fontawesome
Delete-Messages korrigiert
> Diverse Änderungen im Feature-Branch von Tim

- README.md
- app/components/i18n/messages.ts
- app/components/nav/BottomNavigationBar.tsx
- app/components/player/CreatePlayerForm.tsx
- app/components/player/feedback/DefaultFeedbackComponent.tsx
- app/components/player/profile/playerProfileForm.tsx
- app/helpers/constants/fetchLinks.ts
- app/helpers/constants/routeLinks.ts
- app/models/feedback.server.ts
- app/models/games.server.ts
- app/routes/application/admin/games/$gameId.absage.tsx
- app/routes/application/admin/games/$gameId.tsx
- app/routes/application/admin/games/$gameId.zusage.tsx
- app/routes/application/admin/games/new.tsx
- app/routes/application/admin/users/$userId/delete.tsx
- app/routes/application/admin/users/index.tsx
- app/routes/application/admin/users/invites/$inviteId/delete.tsx
- app/routes/application/admin/users/invites/new.tsx
- app/routes/application/admin/users/new.tsx
- app/routes/application/games/$gameId.tsx
- app/routes/application/navbar.tsx
- app/routes/application/notAuthenticated.tsx
- app/routes/application/player/$playerId/delete.tsx
- app/routes/application/player/create.tsx
- app/routes/application/player/profile.tsx
- app/utils/session.server.ts
- prisma/schema.prisma
Berechtigungen so angepasst, dass ein neuer Spieler hinzugefügt werden kann.
Feedback löschen, wenn Spieler gelöscht wird
> Berechtigungen + Löschen angepasst

- app/components/i18n/messages.ts
- app/components/nav/BottomNavigationBar.tsx
- app/components/nav/TopNavBar.tsx
- app/components/nav/appLinks.ts
- app/components/nav/appMenu.tsx
* Neuer Spieler immer sichtbar
* Aktiver Button im BottomNavigationBar.tsx ist jetzt markiert
> aktiver Button + neuer Spieler

- app/components/common/buttons/DefaultButton.tsx
- app/components/common/buttons/SetStatusButton.tsx
- app/components/common/buttons/SuccessButton.tsx
- app/components/common/buttons/submitButton.tsx
- app/components/common/container/ContentContainer.tsx
- app/components/common/container/loadingSkeleton.tsx
- app/components/dashboard/gameFeedback.tsx
- app/components/game/forms/CreateGameForm.tsx
- app/components/i18n/messages.ts
- app/components/nav/BottomNavigationBar.tsx
- app/routes/application.tsx
- app/routes/application/admin/games/$gameId/invite.tsx
- app/routes/application/admin/games/new.tsx
- app/routes/application/admin/users/invites/$inviteId.response.tsx
- app/routes/application/admin/users/invites/new.tsx
- app/routes/application/dashboard/index.tsx
- app/routes/application/games/$gameId/player/$playerId/index.tsx
- app/routes/application/player/profile.tsx
> * Submit-Button zeigt den Transition-Status an

- app/components/player/CreatePlayerForm.tsx
- app/routes/application/player/create.tsx
Neuer Spieler:
* Invite-Mail
* Name + Mail sind Pflichtfelder
> Mail + Pflichtfelder

- app/components/common/buttons/ShakingContainer.tsx
- app/config/routeLinks.ts
- app/helpers/mail/mailServiceHelper.ts
- app/models/mailservice.server.ts
- app/routes/application/admin/games/$gameId/sendMail.tsx
- prisma/schema.prisma
* Mailsender speichert nur noch die Request-ID
* Die Animation ist jetzt up/down
> Djk 94 1: Diverse Anpassungen für das Mailsenden u. Animation

- app/components/common/buttons/ShakingContainer.tsx
- app/config/routeLinks.ts
- app/helpers/mail/mailServiceHelper.ts
- app/models/mailservice.server.ts
- app/routes/application/admin/games/$gameId/sendMail.tsx
- prisma/schema.prisma
> Request-Speicherung

- app/components/common/header/BodyText.tsx
- app/components/i18n/messages.ts
- app/components/player/profile/playerProfileForm.tsx
- app/models/player.server.ts
- app/routes/application/player/$playerId/profile/index.tsx
Fehler beim Speichern der Mail.
Jetzt kann nur noch der Status gesetzt werden, die Mail kann nur von einem Administrator geändert werden
> DJK-99: Bugfix bei der Änderung des Profils, 

- app/components/common/header/pageBanner.tsx
- app/root.tsx
- app/routes/application/admin/games/$gameId/edit.tsx
- app/routes/application/admin/games/$gameId/sendMail.tsx
- app/routes/application/games/$gameId.tsx
- app/utils/game.server.ts
- prisma/schema.prisma
> DJK-114: show game status und info banner

- app/components/common/location/location.tsx
- app/config/index.ts
- remix.config.js
* netlify-config 
* kleinere Fixes
> Djk 114: Nochmal Spielorte
